# -*- coding: utf-8 -*-
"""1st_asg_basic_io.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10wRBeKAvqcmOx4WWYkjf37_kiT09f4Yd
"""

# Install required libraries
!pip install -q transformers langchain accelerate

from transformers import pipeline #importing pipeline utility to load models

# Creating hugging face pipeline
pipe = pipeline(
    "text2text-generation", #task type - input-output text generation
    model="google/flan-t5-large",
    max_length=300,     #length of output
    do_sample=True,        # enable sampling
    temperature=0.7,   #specify randomness of output
    repetition_penalty=1.5  #prevents repeating same sentences
)

#giving input
user_query = input("Enter your question:")
#sending it to model
response=pipe(user_query)

print(response)